config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, param: :name, only: [:index, :show, :edit, :update, :destroy]
  resources :personals, only: :edit
  resources :funerals, only: %i[edit show]
  resources :budgets, only: :edit
  resources :chief_mourners, only: :edit
  resources :ashes, only: :edit
  resources :posthumous_names, only: :edit
  resources :belongings, only: :edit
  resources :legacies, only: :edit
  resources :emotions, :friends

  root to: 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum funeral_wishes:  { conduct: 0, do_not: 1 }
  enum funeral_form:    { general_funeral: 0, family_funeral: 1, mourner: 2 }
  enum ashes:           { grave: 0, ossuary: 1, home: 2, scattered_bones: 3, others: 4 }
  enum posthumous_name: { put_on: 0, put_off: 1 }
  enum belongings:      { dispose: 0, entrust: 1 }

  has_many :emotions
  has_many :friends
end

app/controllers/ashes_controller.rb
class AshesController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  def new
    @emotion = Emotion.new
  end

  def show; end

  def create
    @emotion = current_user.emotions.build(emotion_params)
    if @emotion.save
      redirect_to root_path
    else
      @errors = @emotion.errors.full_messages
      render :new
    end
  end

  private

  def emotion_params
    params.require(:emotion).permit(:emotion_text)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def new
    @friend = Friend.new
  end

  def show; end

  def create
    @friend = current_user.friends.build(friend_params)
    if @friend.save
      redirect_to root_path
    else
      @errors = @friend.errors.full_messages
      render :new
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:friends_name, :contact)
  end
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/legacies_controller.rb
class LegaciesController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: %i[index show]
  before_action :set_user_by_name, only: %i[show edit update destroy]

  def index
    if user_signed_in?
      @users = [current_user]
    else
      @users = []
      render :new
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to '/'
    else
      render :new
    end
  end

  def edit
    # @user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.name), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_user_by_name
    @user = User.find_by(name: params[:name])
    unless @user
      redirect_to root_path, alert: "User not found"
    end
  end
  
  def user_params
    params.require(:user).permit(:strengths, :hobbies, :skills,
                                 :funeral_wishes, :funeral_form, :posthumous_name_budget, :funeral_home_budget, :reword_budget, :others_budget, :chief_mourner, :kinship, :ashes, :posthumous_name, :belongings, :legacy, :emotion)
  end

  def move_to_index
    return if user_signed_in?

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ashes_helper.rb
module AshesHelper
end

app/helpers/belongings_helper.rb
module BelongingsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/chief_mourners_helper.rb
module ChiefMournersHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/legacies_helper.rb
module LegaciesHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/funerals/edit.html.erb
<header class="header" >
  <%= link_to root_path do %>
  <div class="back-btn">戻る</div>
  <% end %>
    <div class="logo">
      <h1>葬式のこと</h1>
    </div> 
</header>    
    
  <div class="personal">
    <div class="funeral-description">
      <h1>葬式とは？</h1>
        <p>故人を尊重し、最後を追悼するために行われる儀式です。</p>
        <p>家族や友人、知人が集まり故人を送るための儀式を行います。</p>
        <p>※宗教や文化、地域により違いはあります。</p>
        <p>簡単に言えば、故人を尊重し最後のお別れをする儀式です。</p>
        <p><%= link_to'葬式のことをもっと知る', funeral_path(current_user) %></p>
    </div>
    <div class="personal-title">
    <h2>葬式の希望を入力する</h2>
    </div>
    <div class="funeral-content">
    <%= form_with(model: @user, local: true) do |form| %>
    <h3>葬式のこと(希望)</h3>
      <%= form.select :funeral_wishes, User.funeral_wishes.keys.map { |k| [t("enum.user.funeral_wishes.#{k}"), k] }, { include_blank: "指定なし" } %>
    <h3>葬式のこと(形態)</h3>
      <%= form.select :funeral_form, User.funeral_forms.keys.map { |k| [t("enum.user.funeral_form.#{k}"), k] }, { include_blank: "指定なし" } %>
      <%= form.submit "保存する", class: "custom-button", style: "display: block;" %>
    <% end %>
    </div>
    </div>
  </div>

app/views/funerals/show.html.erb
<header class="header" >
  <%= link_to root_path do %>
  <div class="back-btn">topへ戻る</div>
  <% end %>
    <div class="logo">
      <h1>葬式を学ぶ</h1>
    </div> 
</header>

<div class="page-show">
<h1>葬式とは?</h1>
<p>葬式と葬儀とは、「死者を葬る儀式」の意味です。</p>
<p>厳密には、葬式とは「葬儀」と「告別式」を合わせた言葉です。</p>
<p>故人の弔いはお通夜、葬儀、告別式から成り立っています。</p>
<p>お通夜以外の儀式をまとめた言葉が一般に「葬式」と呼ばれています。</p>
<P>要するに葬式とは、死者を弔う儀式の総称です。</p>
<h1>葬儀とは?</h1>
<p>故人を見送る儀式のことで、葬式と意味が被ることが多いです。</p>
<p>看取り、納棺、お通夜、葬儀、告別式、火葬、納骨、四十九日と儀式が続きます。</p>
<p>近親者のみが集まり読経挙げてもらう儀式です。</p>
<h1>告別式とは?</h1>
<p>告別式には故人と生前関わりあった人がお別れに訪れる儀式です。</p>
<p>近年では、告別式やお通夜を短縮し、火葬のみを行う「直葬」も増えています。</p>
<p>故人が身寄りがない場合や、葬儀費用を抑えたい場合に直葬を選ぶ傾向があります。</p>
<p>告別式は宗教儀式にあまりとらわれず、故人とお別れをする儀式です。</p>
</div>