config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, param: :name, only: [:index, :show, :edit, :update, :destroy]
  resources :personals, only: :edit
  resources :funerals, only: %i[edit show]
  resources :budgets, only: :edit
  resources :chief_mourners, only: :edit
  resources :ashes, only: :edit
  resources :posthumous_names, only: :edit
  resources :belongings, only: :edit
  resources :legacies, only: :edit
  resources :emotions, :friends

  root to: 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum funeral_wishes:  { conduct: 0, do_not: 1 }
  enum funeral_form:    { general_funeral: 0, family_funeral: 1, mourner: 2 }
  enum ashes:           { grave: 0, ossuary: 1, home: 2, scattered_bones: 3, others: 4 }
  enum posthumous_name: { put_on: 0, put_off: 1 }
  enum belongings:      { dispose: 0, entrust: 1 }

  has_many :emotions
  has_many :friends
end

app/controllers/ashes_controller.rb
class AshesController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  def new
    @emotion = Emotion.new
  end

  def show; end

  def create
    @emotion = current_user.emotions.build(emotion_params)
    if @emotion.save
      redirect_to root_path
    else
      @errors = @emotion.errors.full_messages
      render :new
    end
  end

  private

  def emotion_params
    params.require(:emotion).permit(:emotion_text)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def new
    @friend = Friend.new
  end

  def show; end

  def create
    @friend = current_user.friends.build(friend_params)
    if @friend.save
      redirect_to root_path
    else
      @errors = @friend.errors.full_messages
      render :new
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:friends_name, :contact)
  end
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/legacies_controller.rb
class LegaciesController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  def edit
    @user = User.find_by!(name: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: %i[index show]
  before_action :set_user_by_name, only: %i[show edit update destroy]

  def index
    if user_signed_in?
      @users = [current_user]
    else
      @users = []
      render :new
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to '/'
    else
      render :new
    end
  end

  def edit
    # @user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.name), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_user_by_name
    @user = User.find_by(name: params[:name])
    unless @user
      redirect_to root_path, alert: "User not found"
    end
  end
  
  def user_params
    params.require(:user).permit(:strengths, :hobbies, :skills,
                                 :funeral_wishes, :funeral_form, :posthumous_name_budget, :funeral_home_budget, :reword_budget, :others_budget, :chief_mourner, :kinship, :ashes, :posthumous_name, :belongings, :legacy, :emotion)
  end

  def move_to_index
    return if user_signed_in?

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ashes_helper.rb
module AshesHelper
end

app/helpers/belongings_helper.rb
module BelongingsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/chief_mourners_helper.rb
module ChiefMournersHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/legacies_helper.rb
module LegaciesHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/posthuomus_names_helper.rb
module PosthuomusNamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/emotions/new.html.erb
<header class="header" >
  <%= link_to root_path do %>
  <div class="back-btn">戻る</div>
  <% end %>
    <div class="logo">
      <h1>日々の想い</h1>
    </div> 
</header>

<div class="personal">
    <div class="personal-title">
    <h2>日々の想いを入力する</h2>
    </div>
    <div class="content">
    <%= form_with(model: @emotion, local: true) do |form| %>
      <%= form.text_area :emotion_text, placeholder: "日々想ったことを入力しましょう", rows: 20 %>
      <%= form.submit "保存する", class: "custom-button", style: "display: block;" %>
    <% end %>
    </div>
 </div>

app/views/emotions/show.html.erb
<div class="personal">
    <div class="personal-title">
    <h2>日々の想い、言葉を入力する</h2>
    </div>
    <%= form_with(model: @emotion, local: true) do |form| %>
      <%= form.text_area :emotion, placeholder: "日々想ったことを入力しましょう", rows: 3 %>
      <%= form.submit "保存する", class: "custom-button", style: "display: block;" %>
    <% end %>
    </div>

app/views/friends/new.html.erb
<header class="header" >
  <%= link_to root_path do %>
  <div class="back-btn">戻る</div>
  <% end %>
   <div class="logo">
      <h1>友人・知人</h1>
   </div> 
</header>

<div class="friend-main">
    <h2>友人・知人への連絡について入力しましょう</h2>
    <%= form_with(model: @friend, local: true) do |form| %>
    <div class="friend-content">
      <%= form.text_area :friends_name, placeholder: "友人・知人を入力しましょう" %>
      <%= form.text_area :contact, placeholder: "連絡方法を入力しましょう" %>
    </div>
        <button class="add-btn" type="button">追加</button>
      <%= form.submit "保存する", class: "custom-button", style: "display: block;" %>
    <% end %>
 </div>

app/views/users/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <% stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <%= render'layouts/header' %>
  <body>
    <% @users.each do |user| %>

       <div class="service-items">

       <!-- 自分のこと -->
       <div class="service-item">
         <%= link_to edit_personal_path(current_user.name), class: "link" do %>
         <div class="item-wrapper">
         <p>自分のこと</p>
         <%= image_tag '自分のこと.jpeg', class: "center-image" %>
         </div>
         <button>自分のことを考えましょう。</button>
         <% end %>
       </div>

        <!-- 日々の想い -->
        <div class="service-item">
          <%= link_to new_emotion_path(current_user.name), class: "link" do %>
          <div class="item-wrapper">
          <p>日々の想い・言葉</p>
          <%= image_tag '日々の想い.jpeg' %>
          </div>
          <button>日々の想いを考えましょう。</button>
          <% end %>
        </div>

        <!-- 葬式のこと -->
        <div class="service-item">
          <%= link_to edit_funeral_path(current_user.name), class: "link" do %>
          <div class="item-wrapper">
          <p>葬式のこと</p>
          <%= image_tag '葬式のこと.png' %>
          </div>
          <button>葬式のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 予算 -->
        <div class="service-item">
          <%= link_to edit_budget_path(current_user.name), class: "link" do %>
          <div class="item-wrapper">
          <p>予算</p>  
          <%= image_tag '予算.jpeg' %>
          </div>
          <button>葬式の予算を考えましょう。</button>
          <% end %>
        </div>
          
        <!-- 喪主のこと -->
        <div class="service-item">
          <%= link_to edit_chief_mourner_path(current_user.name), class: "link"  do %>
          <div class="item-wrapper">
          <p>喪主のこと</p>  
          <%= image_tag '喪主.jpeg' %>
          </div>
          <button>喪主のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 遺骨のこと -->
        <div class="service-item">
          <%= link_to edit_ash_path(current_user.name), class:"link" do %>
          <div class="item-wrapper">
          <p>遺骨のこと</p>
          <%= image_tag '遺骨.jpeg' %>
          </div>
          <button>遺骨のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 戒名 -->
        <div class="service-item">
          <%= link_to edit_posthumous_name_path(current_user.name), class:"link" do %>
          <div class="item-wrapper">
          <p>戒名</p>
          <%= image_tag '戒名.jpeg' %>
          </div>
          <button>戒名のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 遺品整理 -->
        <div class="service-item">
          <%= link_to edit_belonging_path(current_user.name), class:"link" do %>
          <div class="item-wrapper">
          <p>遺品整理</p>  
          <%= image_tag '遺品.jpeg' %>
          </div>
          <button>遺品のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 遺産 -->
        <div class="service-item">
          <%= link_to edit_legacy_path(current_user.name), class:"link" do %>
          <div class="item-wrapper">
          <p>遺産</p>
          <%= image_tag '遺産.jpeg' %>
          </div>
          <button>自分の遺産のことを考えましょう。</button>
          <% end %>
        </div>

        <!-- 友人・知人 -->
        <div class="service-item">
          <%= link_to new_friend_path(current_user.name), class:"link" do %>
          <div class="item-wrapper">
          <p>友人・知人</p>
          <%= image_tag '友人.jpeg' %>
          </div>
          <button>友人・知人のことを考えましょう。</button>
          <% end %>
        </div>
      </div> 
     </div>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<%= render'layouts/header'%>
<div class="top-page">
  <div class="container">
   <h3>
    <p>質問です。</p>
    <p>あなたは本当に「自分の人生」を生きているでしょうか？</p>
    <p>LifeTimeは自分の人生の最後、お葬式のことを考えるアプリです。</p>
    <p>自分のお葬式を考えることは</p>
    <p>「きっかけ・手段」であり目的ではありません。</p>
    <p>普段考えないお葬式のことを考えながら</p>
    <p>「自分の人生を生きる」ことを考えて見つめるアプリです。</p>
    <p>できれば考えたことを自分の身近な大切な人に共有してほしいです。</p>
    <p>そして大切な人とぜひ話すきっかけにしてください。</p>
    <p>「他人の人生を生きる」のではなく、「自分の人生を生きる」。</p>
    <p>そのお手伝いができれば幸いです。</p>
    <p>あなたの人生に"幸あれ"。</p>
   </h3>
  </div>
</div>

app/views/users/show.html.erb
<%= render'layouts/header'%>
  <div class="mypage">
    <% if @user %>
      <p>名前: <%= @user.name %></p>
      <P>長所: <%= @user.strengths %></p>
      <P>趣味: <%= @user.hobbies %></p>
      <P>特技: <%= @user.skills %></p>
      <p>葬式の希望: <%= @user.funeral_wishes.present? ? t("enum.user.funeral_wishes.#{@user.funeral_wishes}") : '' %></p>
      <P>葬式の形態: <%= @user.funeral_form.present? ? t("enum.user.funeral_form,#{@user.funeral_form}") : '' %></p>
      <P>戒名の予算: <%= @user.posthumous_name_budget %></p>
      <P>葬儀場の予算: <%= @user.funeral_home_budget %></p>
      <P>謝礼の予算: <%= @user.reword_budget %></p>
      <P>その他の予算: <%= @user.others_budget %></p>
      <p>喪主の氏名: <%= @user.chief_mourner %></p>
      <p>喪主との関係: <%= @user.kinship %></p>
      <p>遺骨の希望: <%= @user.ashes.present? ? t("enum.user.ashes.#{@user.ashes}") : '' %></p>
      <p>戒名の希望: <%= @user.posthumous_name.present? ? t("enum.user.posthumous_name.#{@user.posthumous_name}") : '' %></p>
      <p>遺品のこと: <%= @user.belongings.present? ? t("enum.user.belongings.#{@user.belongings}") : '' %></p>
   <% else %>
     <p>ユーザーが見つかりません。</p>
   <% end %>
</div>